require_relative 'culture_news_reader/version'
require_relative 'culture_news_reader/cli'
require_relative 'culture_news_reader/scraper.rb'
require_relative 'culture_news_reader/article.rb'
require_relative 'culture_news_reader/category.rb'
